version: '3.8'

services:

  web:
    build: .
    ports:
      - 8000:8000
    command: fastapi dev --reload --host 0.0.0.0
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A app.task.app worker --loglevel=info --concurrency=2
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:7
    ports:
      - 6379:6379
  # celery:
  #   build: .
  #   command: celery --app=app.task.app worker --concurrency=1 --loglevel=info
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - redis

  # app:
  #   build: .
  #   command: fastapi run --reload --host
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - redis
  #     - celery
